### ISSUE TITLE
Documentation Update: How do we run this bad boy?

### ISSUE THREAD

**Issue by nbgibson** [netbymatt/ws4kp#12]
Before requesting a feature please consider that this is not intended to be a perfect recreation of the WeatherStar 4000, it's a best effort that fits within what's available from the API and within a web browser.

**Comment by netbymatt** [comment]
Good question. I'll get it in to the documentation but here's the short form once you've got Node.js installed.
```
git clone https://github.com/netbymatt/ws4kp.git
cd ws4kp
node index.js
```
Then open your browser and go to https://localhost:8080/
