### ISSUE TITLE
Fullscreen button always says "Exit Fullscreen" on hover

### ISSUE THREAD

**Issue by wiichicken** [netbymatt/ws4kp#17]
The fullscreen button always shows the icon for exiting fullscreen, even if I am not in fullscreen. The tooltip always says "Exit fullscreen" as well
![image](https://user-images.githubusercontent.com/50886841/200143260-5cad2790-d6d5-46fe-a7d8-7e46a9d78ded.png)
This seems to happen for every location I select. 

**Browser**:
- Vivaldi, Windows 10

*I have also had this happen on Safari on iOS*
**Locations**:
*This happens regardless of location*

**Comment by netbymatt** [comment]
a4f1035e74eed9e6012b11c0195bf49efb31c732
