### ISSUE TITLE
Fullscreen does not expand

### ISSUE THREAD

**Issue by N7KnightOne** [netbymatt/ws4kp#25]
Please see the referenced screenshot
![image](https://github.com/netbymatt/ws4kp/assets/47005674/03ce74db-bda7-43e5-a36f-d993ffe46353)

When activating full screen on the application, it does not expand at all. 

Web Browser: Firefox
OS: Archlinux
Forecast Location: Everett, WA

**Comment by netbymatt** [comment]
I see this happening in Firefox on Ubuntu 22.04 as well. It's probably a CSS thing. I'll check it out.

**Comment by netbymatt** [comment]
2c010a9a32a8405cda99fcac85d07cc5106df5ae I was using css zoom, which is non-standard. This has been changed to transform: scale() along with some other supporting CSS because zoom and transform effect the box model slightly differently.
