### ISSUE TITLE
Setting up on Linux shared host

### ISSUE THREAD

**Issue by mmarron79** [netbymatt/ws4kp#31]
I'm trying to set this up on a shared Linux host. I keep getting a 404 error. My host's tech support says I have the application setup correctly, and that it must be a coding error. I tried Node versions 12.22.9 and 14.21.2. I also tried development and production modes. Nothing changes. The readme mentions running it on a local machine, but not on a web host, so I feel like I'm missing a step. Please advise.

Matt

**Comment by netbymatt** [comment]
There's a lot of pieces to hosting this that need to fall into place. They're all more under the scope of "hosting a nodejs app on shared hosting" of which there an and endless number of guides available.

Here are the general pieces to getting it done. Any one of which would cause problems with it running successfully.

- Is the app running in node. Note that if you use SSH to start the app, then close the SSH window node will close with it. There are ways around this such as pm2
- Are you going to <yourdomain.com>:8080 or:
    - Have you set up your web server to run a "reverse proxy" to this address
    - Have you changed the port by using the environment variable WS4KP_PORT
- Are you running on https? This is not necessary, except that browsers won't allow the gps location lookup to work on non-https connections.

**Comment by mmarron79** [comment]
I setup the app in cpanel. As far as I know, it runs all the time and uses the standard port. The domain uses https. Since I didn't set it up through SSH, I didn't realize I had to install other packages (I'm not new to javascript, but am new to Node). It appears the issue is with installing the packages. My host says some packages (mentioned in package.json I assume) are no longer in use or outdated. I tried upgrading to the latest version they had available, but I got the same generic error. Interestingly, I was able to get it setup on my computer in about 20 minutes. The only problem I ran into was needing to reinstall some of the packages.

**Comment by mmarron79** [comment]
We got the packages installed. Apparently the issue now is the port number referenced in index.js. Since my app url doesn't use a port, I assume this should be 80, but that didn't work (I get a 404 error).

**Comment by mmarron79** [comment]
My hosting company was never able to figure out the problem, so I've given up on hosting the app. Fortunately, I figure out that I can technically run it using the files in the dist folder. Now my problem is figuring out how to refresh that folder when I make changes to the app code. Is there a command I can run to make that happen?

**Comment by netbymatt** [comment]
Instead of grabbing the zip file and unpacking it on your server, use git to get a copy of it and then later manage the updates.

Once git is installed on your server start with
`git clone https://github.com/netbymatt/ws4kp.git`
Which will get a copy of this code and put it in the /ws4kp subdirectory from where you run this command.

Then when you want to update use `git pull` to update files to the latest version.

**Comment by mmarron79** [comment]
Thanks for the reply, but I don't want to update it based on changes you make. I want to update the files in the dist folder based on changes I make locally. Maybe the question I need to ask is how do the files in dist (like index.html and ws.min.js) get created or updated?

**Comment by netbymatt** [comment]
81561f75a1e00b0bcbf658b313e049ba11d7ebab added a new gulp task that only builds the dist folder. This is the error free way to accomplish what you're asking.
```
npx gulp build-dist
```

**Comment by mmarron79** [comment]
Thanks! When I run either command, I get the following error:

Cannot find module: './lib/reorder'

**Comment by mmarron79** [comment]
I figured it out! I needed to reinstall another batch of modules.
