### ISSUE TITLE
Optional 16:9 aspect ratio

### ISSUE THREAD

**Issue by mattatobin** [netbymatt/ws4kp#32]
I would like to request an optional feature to have it in a wide screen aspect just simply by extending the gradient background and bar out on the sides nothing radical requiring redesign same blue box and positioning just on a wider background.

**Comment by netbymatt** [comment]
I like this. It's a really simple way to make it look better on modern devices with minimal effort. I'll look over the CSS and cross my fingers that I didn't hard-code too much width data.

**Comment by netbymatt** [comment]
Added a checkbox below the weather display check boxes. It's sticky, so it will remember the setting between visits.

**Comment by mattatobin** [comment]
OUTSTANDING! Thank you so much!
