### ISSUE TITLE
is there a way to turn this into a ffmpeg stream?

### ISSUE THREAD

**Issue by stoneobscurity** [netbymatt/ws4kp#37]
1] is there way to turn the widescreen div area into a ffmpeg stream? something i could open up in VLC as a network stream.

2] how do i pass in the location and checkbox settings to do automated startup? querystring? conf file? docker -e configs?

**Comment by netbymatt** [comment]
1. This isn't on my roadmap
2. This is being worked in on #33

**Comment by zshall** [comment]
@stoneobscurity I wanted to make a video stream too and figured out a way to get it done, though it requires some setup. Here's how I did it:

* Create a Ubuntu 22.04 virtual machine, bridged to your LAN
* Install Docker
* Get `ws4kp` running as a Docker image on the port of your choosing
* Install [Monaserver](https://github.com/MonaSolutions/MonaServer2) as a Docker image on the default ports
* Install [OBS Studio](https://obsproject.com/download) in the VM; set the streaming address to `rtmp://localhost` with stream key `weather`. Note that you need to install OBS from the PPA source (instructions in that link), not through the default `apt` package for the next steps to work properly.
* Set a base (canvas) resolution of 640x480 under OBS's video settings
* Add a Browser source that's 640x520 and point it to your `ws4kp` instance, e.g. `http://localhost:8080`
* Right click on the Browser source and select the "Interact" option. Now, use the interface to input your desired location.
* Move the Browser source **down**, moving the location bar out of view. Position the WeatherStar display in the center of the canvas.
* Click "Start Streaming" with Monaserver running.
* On a your target computer, open VLC or a different player that supports MP4 streaming and open `http://[vm-hostname]/weather.mp4`, assuming that you have Monaserver bridged to port 80.
* It should be playing!

![image](https://github.com/netbymatt/ws4kp/assets/175742/90f631b7-719f-4431-8263-ce74906c7120)

**Caveats**

* If you restart OBS, it seems that the WeatherStar display scales to almost the full width and height but not quite, so you need to resize the browser source twice to fix the issue. Moving the location bar below the display (modifying the project) may help.

**Comment by Sonny-Crockett** [comment]
Awesome work zshall! 

Is it possible to use https://github.com/AlexxIT/go2rtc for any part of this? I am already using it for another project and just trying to double up where I can haha.

**Comment by rmitchellscott** [comment]
@Sonny-Crockett Not exactly what you asked for, but I did create a docker container that streams the website over RTMP, and can optionally inject audio (the weatherscan tracks, for example) in via Icecast: https://github.com/rmitchellscott/pagecaster

**Comment by Sonny-Crockett** [comment]
> [@Sonny-Crockett](https://github.com/Sonny-Crockett) Not exactly what you asked for, but I did create a docker container that streams the website over RTMP, and can optionally inject audio (the weatherscan tracks, for example) in via Icecast: https://github.com/rmitchellscott/pagecaster

Thanks! Thats awesome, I can think of SO many uses for that! I saw you mention possible Intel QSV as a long term goal. +1 for that. I use that in all my servers, so definitely something great to have in regard to performance.

**Comment by kineticman** [comment]
Check this out for a containerized version of this that exports to a .m3u for streaming.  Thanks Rice!

https://github.com/rice9797/ws4channels

**Comment by netbymatt** [comment]
This has been added to the readme 91f669e8282932b4decae6beca0bf7f610f7a81b
