### ISSUE TITLE
Permalink for Kiosk Mode

### ISSUE THREAD

**Issue by Node815** [netbymatt/ws4kp#38]
I set this up and am embedding this into an iframe in a Home Assistant dashboard which loads well, but there doesn't seem to be a way to tell it to open it in Kiosk mode upon page load/reload.     Can this be added or is there a way to do this by appending something like ?kiosk after the url  https://weather.example.com/?kiosk

**Comment by netbymatt** [comment]
Glad to hear it's working in an iframe. Permalinks and kiosk mode are covered in the documentation. https://github.com/netbymatt/ws4kp?tab=readme-ov-file#kiosk-mode
