### ISSUE TITLE
retry api.weather.gov on failure (http 500)

### ISSUE THREAD

**Issue by bgutman** [netbymatt/ws4kp#40]
On the weather.gov documentation page for api ( https://www.weather.gov/documentation/services-web-api ) on the updates tab there is known bug of getting 500 errors and the "fix" is to retry the api call.
"The gridpoints endpoint returns a 500 error. Retrying the request generally returns valid data."

Please see https://weatherspotter.net/ngitws_api_gridpoints_retry_performance.php  With retries (2 retries) the api is in the 99-100% reliable range.

Please include:
* Web browser and OS
   Windows 11 Chrome/Firefox/Edge
* Location for which you are viewing a forecast
   any random US location.

**Comment by netbymatt** [comment]
I learned this with my other weather project. Unfortunately it's not cut and dry. Most of the time it will return data in these situations after waiting about 10 seconds. I do have some exponential back off and retry code over there that I could bring in.

**Comment by netbymatt** [comment]
Turns out I'm already using retry code.

https://github.com/netbymatt/ws4kp/blob/20b4d22115c6dfeb2e3e1fe14b6a97993b1a0821/server/scripts/modules/utils/fetch.mjs#L53-L77

Are you seeing 500 errors that are ultimately keeping weatherstar from loading?

**Comment by bgutman** [comment]
It run for a while (hrs) and then local forecasts fail. I hit refresh and it works again. From encountering 500 errors with api.weather.gov, on other projects it felt like same behavior.  I was running in docker container didn't see enough output to know what happened. Will try running in vscode and see if I capture anything.
