### ISSUE TITLE
Have a button where the player is 100% of the viewport

### ISSUE THREAD

**Issue by mattatobin** [netbymatt/ws4kp#42]
For purposes of running in a window.. I think would be nice if there was a button that instead of full screened just expanded the player to the full height and width of the window or say under a tiling window manager of some sort.

**Comment by netbymatt** [comment]
Have you tried the [Kiosk](https://github.com/netbymatt/ws4kp?tab=readme-ov-file#kiosk-mode) option? When I turn that on in a regular window the weather displays fill up the available space in the window, letterboxing to keep the aspect ratio. I can freely resize the window and the display continues to fill the available area.

**Comment by mattatobin** [comment]
So what you are saying is to fully resolve the issue I should read the readme and plan to check said readme before making feature requests? LOL Sorry for the redundant noise ;)

**Comment by netbymatt** [comment]
It's not all noise. Someone else who goes searching for the same window, viewport or 100% idea can now discover this solution and find that it's called kiosk.
