### ISSUE TITLE
Audio Playlist Feature (Locally Hosted versions)

### ISSUE THREAD

**Issue by tlozwarlock** [netbymatt/ws4kp#43]
First off, great fork of the original. I'm currently using it in Kiosk mode at the house because having my own WS4000+ approximation running on a thoroughly repurposed arcade cabinet just fits the bill for someone of my particular age group.

With the taiganet standalone of the WS4000 all but dead now, in my search for a modern, web based (and NWS API-hooked) iterations of it are sans soft-jazz tinkling. It's a must in my opinion to have some elevator music going along with my "Local on the 8's!" ever-looping arcade weather machine.

Is there any desire for the locally-hosted version of this to support any playlisting or music embedding features? Perhaps a section in the config that lets you load a m3u or file folder native to the local server that can side-play your favorite Weather Channel tunes while you nostalgia-gaze? 

I know this is easily resolved with a playlist loaded with my media player of choice in the background but having the music dependent upon the page running makes startup and shutdown much easier.

**Comment by netbymatt** [comment]
Thanks for the praise!

I don't plan to add playlists. I don't want to incorporate the music into this repo for size and possible copyright situations. Also, there's so many ways to do playlists: play from disk, open Spotify, embed in the web page... I would get outside what I feel is the core project I'm working on.

However, there is a mechanism to add custom code to the weatherstar. It's currently not documented but I used to add github links to my hosted copy of the project. The app tries to load a file called `custom.js` and if it's there it'll execute that code. What I'll do is put some "boilerplate" code in here and publish it along with documentation so things like this can be integrated.

**Comment by tlozwarlock** [comment]
That sounds like a great compromise. Let us tack on whatever our individual situations require. Thanks!
