### ISSUE TITLE
Changing out logo

### ISSUE THREAD

**Issue by ksutto3** [netbymatt/ws4kp#44]
Is it possible to swap out the logo for a custom option?

**Comment by netbymatt** [comment]
This quick and easy way would be to just drop in a file in place of images/Logo3.png

The more permanent way is available now through custom.js but I have not put together documentation for that. See  https://github.com/netbymatt/ws4kp/issues/43#issuecomment-2107612071

**Comment by JohnTErskine** [comment]
Is it possible to specify a volume in docker like was done for the music? That would allow for personalization of image assets if desired?
