### ISSUE TITLE
Over Time Simulator Slows Down

### ISSUE THREAD

**Issue by nick02124** [netbymatt/ws4kp#45]
Firefox, Windows 10

Sometimes I like running this emulator on another computer connected to a small display for a long time. The issue is after about a day the emulator becomes slow. This seems to only occur on 2 slides, the hourly and travel forecast. The scrolling is really slow and makes it take minutes to get through. I have to refresh the page to fix it.

**Comment by netbymatt** [comment]
Can you see if this is fixed in v5.11.4?

**Comment by nick02124** [comment]
Sorry for the wait, it appears to work just fine now. Thanks!
