### ISSUE TITLE
Kiosk Mode

### ISSUE THREAD

**Issue by holocronology** [netbymatt/ws4kp#46]
I have this installed on Unraid using an assigned macvlan address. 192.168.2.200, for example.

So to get to it I go to http://192.168.2.200:8080. Works great from there.

However, I am unable to get kiosk mode to work correctly. If I check kiosk mode it will switch but I am unable to force it into kiosk mode from a URL. Any new call to the url or refresh kicks it out of kiosk mode.

If there a trick to this?

Maybe an alternative port could be utilized for kiosk mode?

**Comment by netbymatt** [comment]
You have to modify the URL slightly to use kiosk mode. It's a manual action because you can't click the "Copy Link" button once you're in kiosk mode. It's documented in the [Readme](https://github.com/netbymatt/ws4kp?tab=readme-ov-file#kiosk-mode)

**Comment by holocronology** [comment]
The URL modification in the Readme is not working. Perhaps I was unclear about that in my initial comments.

I get an error:
`Cannot GET /&kiosk=true`

**Comment by netbymatt** [comment]
If your not also using a permalink then it's /?kiosk=true since it's the only URL parameter.

**Comment by Sonny-Crockett** [comment]
I found this issue and fixed my install from unRAID. If you would not mind adding that into the readme, that would be great, as I was putting in "&kiosk=true" as well and getting the same error. Hopefully it would help others that might not think to look for the issue. 

It is now working great inside of an iframe on my selfhosted dashboard!

**Comment by holocronology** [comment]
I swear I tried http://192.168.2.200:8080/?kiosk=true multiple times and it didn't work...but now it is.` ¯\_(ツ)_/¯`

**Comment by Sonny-Crockett** [comment]
What would a URL look like with Kiosk and Widescreen in it? When I check ✅ Widescreen, it does not affect the PERMALINK(at least on the unRAID docker).
