### ISSUE TITLE
Slide Speed Customization

### ISSUE THREAD

**Issue by andrewlittlejohn** [netbymatt/ws4kp#49]
Love the hard work you've put into this.  Sometimes the NOAA descriptions are long and I read slow.  Requesting an option to increase to increase the time on each slide.  If it is possible in the customization script I will update that, but alas, I do not know how.

**Comment by netbymatt** [comment]
This is a good idea. For simplicity I'll implement it as global speed control with 3-5 options: Slow, Normal, Fast. I'll play with this a bit and try to figure out how big the step sizes should be.

If you want to try something slower manually, edit this line:
https://github.com/netbymatt/ws4kp/blob/b62339af948d130f3c6b7dfdaacb2687698485c7/server/scripts/modules/localforecast.mjs#L13
The 5000 is in milliseconds per page. Increase it to slow it down. If you find something that's comfortable for you let me know and I'll use it to tune the speed options.
