### ISSUE TITLE
New Jersey only showing airports 

### ISSUE THREAD

**Issue by moe92n89** [netbymatt/ws4kp#50]
I would first like to say, I absolutely love this project. It is very accurate to TWC's original UI, this site + smooth jazz is incredible. When I select any town in New Jersey, it selects airports near. The latest observations only show airports when the airport is selected. This does not happen on an older version of WS 4000, the version on https://battaglia.ddns.net/twc/#
![Screenshot 2024-08-26 161438](https://github.com/user-attachments/assets/7e1b8528-9293-4035-8f54-b1e658543619)

**Comment by netbymatt** [comment]
I'm pretty sure those are all airports in the list you show. Atlantic city
international airport gets cut off after airport, there's a regional
airport in there, Philadelphia international, and an air force base. This
is where the majority of temperature observation stations are listed so
this is normal behavior.

**Comment by moe92n89** [comment]
It seems like any state or city I select, it only shows airports. When I use version 1.79, this problem does not persist.
