### ISSUE TITLE
Certain Locations Reporting Zeros

### ISSUE THREAD

**Issue by NSSTIG8R** [netbymatt/ws4kp#54]
I'll open up with this, I absolutely LOVE this project. I've been streaming this for a year or more, with credit given to you of course. :) This brings back so many good memories and nostalgia. I wish I could contribute to the code more than just being a user and testing, but I only know basics. Anyways,

So for several months now, certain locations have consistent, permanent like, errors in the data being shown. For example, Myrtle Beach, SC, from the only weather source for the area, KMYR Int'l Airport, it shows 0% humidity, 32 degrees dew point, and 0.00 pressure. It has been like this for months, and if you've ever been to or lived in MB during the summer, it is the farthest from 0% humidity. Haha I looked at what the API is pushing out, and it is showing the proper and current conditions correctly. Not sure if this might be an issue in how WS4KP is parsing the API stream or not, and data is getting lost.

I am using Firefox 131.0.3 on Windows 11.

Thank you for your time with this! I know it isn't your primary thing to do and do it in your spare time. You're doing the Lord's work Matt! Love it! Thank you!

**Comment by netbymatt** [comment]
Thank you for the praise!

This is a good catch. There is some filtering of the data from the observation station, but it was the same filtering used on the "Latest Observations" page, which only needs temperature, wind and a sky condition. I added filtering for blank values for dewpoint and pressure. This causes it to try the next nearest station. So you'll notice the data for Myrtle Beach no longer comes from the international airport, per the screen's title, but now comes from "North Myrtle Beach Grand Strand Airport" although the long name is truncated.

If the international airport starts producing data for dewpoint and pressure again it'll return as the default for current conditions page automatically.

If you want further discussion on why that station stopped reporting data you can bring that up at the API's github page  https://github.com/weather-gov/api/discussions
You'll want to let them know this is the problematic endpoint: https://api.weather.gov/stations/KMYR/observations/latest
