### ISSUE TITLE
Scrolling Temp Display 

### ISSUE THREAD

**Issue by ibezdechi** [netbymatt/ws4kp#58]
* Web browser and OS
* Location for which you are viewing a forecast

MS Edge on Android device
San Diego International Airport

The scrolling daily temperature display and the Travel City display stops prematurely at Indianapolis and only displays half of the line of characters. 

Your app so ROCKS!

**Comment by netbymatt** [comment]
Thanks! I'm seeing this too. It looks to be a problem when it's scaled for different screen sizes such as mobile and full screen. At 100% on desktop it makes it to the end (Washington DC).

It should be a pretty straightforward fix by adding the scaling into the scrolling calculations.
